version: '3.10'

services:
  app:
    build: .
  db:
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${POSTGRE_PASSWORD}
      - POSTGRES_USER=${POSTGRE_USERNAME}
    image: postgres:14.5