"""Count tokens

Revision ID: 746f259614e4
Revises: ae9b15bfb2a8
Create Date: 2023-05-23 22:48:06.743153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746f259614e4'
down_revision = 'ae9b15bfb2a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserContexts', sa.Column('tokens', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserContexts', 'tokens')
    # ### end Alembic commands ###
