"""Refactor for redis

Revision ID: 9de9d1eb5df7
Revises: 746f259614e4
Create Date: 2023-05-29 13:42:53.481439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de9d1eb5df7'
down_revision = '746f259614e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserContexts', 'tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserContexts', sa.Column('tokens', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
