name: Deploy

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        USERNAME: ${{ secrets.VPS_USER }}
        PORT: ${{ secrets.VPS_PORT }}
        PASSWORD: ${{ secrets.SSH_PASS }}
        script: |
          cd ~/projects/gptishka 
          git pull
          docker build -t metravod/gptishka:latest .
          

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        USERNAME: ${{ secrets.VPS_USER }}
        PORT: ${{ secrets.VPS_PORT }}
        PASSWORD: ${{ secrets.SSH_PASS }}
        script: |
          docker-compose up -d
