name: Deploy

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        USERNAME: ${{ secrets.VPS_USER }}
        PORT: ${{ secrets.VPS_PORT }}
        PASSWORD: ${{ secrets.SSH_PASS }}
        script: |
          cd ~/projects/gptishka 
          git pull
          alembic upgrade head
          docker build -t metravod/gptishka:latest .
          docker rm $(docker container ls --filter 'status=exited')
          docker rmi -f $(docker images -f 'dangling=true' -q)
          

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        USERNAME: ${{ secrets.VPS_USER }}
        PORT: ${{ secrets.VPS_PORT }}
        PASSWORD: ${{ secrets.SSH_PASS }}
        script: |
          docker stop gptishka
          docker rm gptishka
          docker run --name gptishka -d metravod/gptishka:latest
