name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: metravod/gptishka:latest

  deployDev:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: Development
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: Run container
      uses: appleboy/ssh-action@master
      env:
        bot: ${{ secrets.BOT }}
        admin: ${{ secrets.ADMIN }}
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        envs: host, admin
        script: |
          docker pull metravod/gptishka:latest
          docker run --env BOT=bot --env ADMIN=admin --name gptishka -d metravod/gptishka:latest

  deployProd:
    name: Deploy to Prod
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: Production
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: Run container
      uses: appleboy/ssh-action@master
      env:
        bot: ${{ secrets.BOT }}
        admin: ${{ secrets.ADMIN }}
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        envs: host, admin
        script: |
          docker pull metravod/gptishka:latest
          docker run --env BOT=bot --env ADMIN=admin --name gptishka -d metravod/gptishka:latest